name: Build and Release Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install specific Capacitor version
      run: |
        npm install -g @capacitor/cli@5.0.0
        npm install -g @capacitor/core@5.0.0
        npm install -g @capacitor/android@5.0.0

    - name: Create Capacitor project
      run: |
        # 创建临时目录
        mkdir -p temp-app
        cd temp-app
        
        # 初始化 npm 项目
        npm init -y
        
        # 安装 Capacitor
        npm install @capacitor/core@5.0.0 @capacitor/cli@5.0.0 @capacitor/android@5.0.0
        
        # 初始化 Capacitor (使用兼容的选项)
        npx cap init "学生成绩可视化系统" "com.example.scorevisualizer" --web-dir public --yes
        
        # 添加 Android 平台
        npx cap add android
        
        # 复制项目文件
        mkdir -p public
        cp -r ../* public/
        rm -rf public/android public/.github
        
        # 同步 Capacitor
        npx cap sync
        
        # 验证目录结构
        echo "当前目录: $(pwd)"
        ls -la
        echo "public 目录:"
        ls -la public
        echo "Android 目录:"
        ls -la android/app/src/main/assets/public

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Make Gradle Wrapper Executable
      run: chmod +x temp-app/android/gradlew

    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > temp-app/android/app/my-release-key.keystore
        echo "storeFile=my-release-key.keystore" >> temp-app/android/local.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> temp-app/android/local.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> temp-app/android/local.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> temp-app/android/local.properties

    - name: Build Android APK
      run: |
        cd temp-app/android
        ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: score-visualizer-app
        path: temp-app/android/app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: temp-app/android/app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: score-visualizer-v${{ github.run_number }}.apk
        asset_content_type: application/vnd.android.package-archive
