name: Cordova Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: ''  # 禁用缓存

      # 3. 安装 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: '25.2.9519653'
          cmake-version: '3.22.1'

      # 4. 配置环境变量
      - name: Configure Android ENV
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.daemon=false" >> $GITHUB_ENV

      # 5. 安装 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 6. 安装 Cordova
      - name: Install Cordova
        run: |
          npm install -g cordova@12.0.0
          cordova telemetry off

      # 7. 初始化 Cordova 项目 (修复版)
      - name: Initialize Cordova project
        run: |
          # 创建 Cordova 项目结构
          cordova create cordova-app com.example.scorevisualizer "学生成绩可视化系统"
          
          # 复制项目文件到 Cordova 的 www 目录 (排除 cordova-app 目录)
          rsync -a --exclude='cordova-app' --exclude='.git' --exclude='.github' ./ cordova-app/www/
          
          # 复制 config.xml 到 Cordova 项目根目录
          if [ -f "config.xml" ]; then
            cp config.xml cordova-app/
          fi
          
          # 进入 Cordova 项目目录
          cd cordova-app
          
          # 验证文件复制
          echo "项目文件列表:"
          ls -la www/
          echo "config.xml 文件:"
          if [ -f "config.xml" ]; then
            cat config.xml
          else
            echo "未找到 config.xml 文件"
          fi

      # 8. 添加 Android 平台
      - name: Add Android platform
        run: |
          cordova platform add android@12.0.0
          cordova requirements android

      # 9. 接受 Android 许可
      - name: Accept Android licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # 10. APK 签名设置
      - name: Set up signing
        if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore.keystore
          if [ ! -s "keystore.keystore" ]; then
            echo "密钥库文件为空或不存在"
            exit 1
          fi
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      # 11. 构建 APK
      - name: Build APK
        env:
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-Xmx3072m -XX:MaxMetaspaceSize=1024m"
        run: |
          cordova clean android
          
          if [ -f "keystore.keystore" ]; then
            cordova build android --release \
              -- --keystore=keystore.keystore \
              --storePassword=${{ secrets.STORE_PASSWORD }} \
              --alias=${{ secrets.KEY_ALIAS }} \
              --password=${{ secrets.KEY_PASSWORD }}
          else
            cordova build android --debug
          fi
          
          # 验证 APK 文件
          if [ ! -f "platforms/android/app/build/outputs/apk/release/app-release.apk" ] && [ ! -f "platforms/android/app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "APK 文件未生成"
            exit 1
          fi

      # 12. 上传构建产物
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            platforms/android/app/build/outputs/apk/**/*.apk
          retention-days: 7
          if-no-files-found: error
