name: Cordova Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 安装 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 4. 配置环境变量
      - name: Configure Android ENV
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      # 5. 安装 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 6. 安装 Cordova
      - name: Install Cordova
        run: npm install -g cordova@12.0.0

      # 7. 添加 Android 平台
      - name: Add Android platform
        run: |
          cordova platform add android@12.0.0
          
      # 8. 接受 Android 许可
      - name: Accept Android licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      # 9. APK 签名设置
      - name: Set up signing
        if: github.event_name == 'release'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore.keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      # 10. 构建 APK
      - name: Build APK
        env:
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-Xmx3072m"
        run: |
          if [ -f "keystore.keystore" ]; then
            cordova build android --release \
              -- --keystore=keystore.keystore \
              --storePassword=${{ secrets.STORE_PASSWORD }} \
              --alias=${{ secrets.KEY_ALIAS }} \
              --password=${{ secrets.KEY_PASSWORD }}
          else
            cordova build android
          fi

      # 11. 上传构建产物 (v4修复版)
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            platforms/android/app/build/outputs/apk/**/*.apk
          retention-days: 7
