name: Cordova Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 安装 Android SDK（关键！）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. 配置环境变量
      - name: Configure ENV
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      # 5. 安装 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 6. 安装 Cordova
      - name: Install Cordova
        run: npm install -g cordova@12.0.0  # 指定兼容版本

      # 7. 恢复依赖缓存（加速构建）
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 8. 添加 Android 平台
      - name: Add Android platform
        run: |
          cordova platform add android@12.0.0

      # 9. 【可选】APK 签名（正式包）
      - name: Set up signing
        if: github.event_name == 'release'  # 仅release时签名
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.keystore | base64 -d
        env:
          KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      # 10. 构建 APK
      - name: Build APK
        run: |
          if [ -f "keystore.keystore" ]; then
            cordova build android --release \
              -- --keystore=keystore.keystore \
              --storePassword=${{ secrets.STORE_PASSWORD }} \
              --alias=${{ secrets.KEY_ALIAS }} \
              --password=${{ secrets.KEY_PASSWORD }}
          else
            cordova build android
          fi

      # 11. 上传产物
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: |
            platforms/android/app/build/outputs/apk/debug/*.apk
            platforms/android/app/build/outputs/apk/release/*.apk
